### PR TITLE
Update wpn_smokegrenade.cpp

### PR DESCRIPTION
**Pull request by afwn90cj93201nixr2e1re**

### CODE REVIEW

**Comment by wopox1337** [comment]
Srzly?) For what?

**Comment by afwn90cj93201nixr2e1re** [comment]
strelba lyshe stanet.

**Comment by wopox1337** [comment]
@afwn90cj93201nixr2e1re Compilyator je me rugaitsya

**Comment by afwn90cj93201nixr2e1re** [comment]
9 iz hegrenade vz9l. convertut navernoe, xz.

**Comment by Vaqtincha** [comment]
bezpolezno

**Comment by theshadowz** [comment]
So, m_flStartThrow should be changed everywhere too

**Comment by Vaqtincha** [comment]
poxoje na kakoy to test pered bolwim commitom.

**Pull request closed without merging**
