### PR TITLE
Add more sv_alltalk modes

### PR DESCRIPTION
**Pull request by In-line**
### New modes:

2. The teammates hear each other (dead hear alive vise versa)
3. Same as 2, but spectators hear everybody.

This PR will get good use in Clan War servers.
Idea was suggested by N3UR0.

### CODE REVIEW

**Comment by shelru** [comment]
Why you think that we need additional cvar values? Maybe just make an API, everyone can do what he needs.

**Comment by In-line** [comment]
There is already API for CanPlayerHearPlayer, but it's convenient to have them without third-party modules/plugins. Because of missing feature like this players use TeamSpeak or another soft to communicate with each other. I guess cw servers are pretty​ common.

**Comment by justgo97** [comment]
isnt better to use flags like for example "a" = "hear dead", "b" = "hear alive", "c" "hear spec" ect.. so you can combine two flags "abc"

**Comment by In-line** [comment]
@justgo97 How we can specify teams like that ? Or situation when dead should hear alive, but not vice versa?

**Comment by justgo97** [comment]
a flag for each team/situation ?

**Comment by IgnacioFDM** [comment]
I think the flag solution is overcomplicated.

**Pull request closed without merging**
