### PR TITLE
in regards to issue #107

### PR DESCRIPTION
**Pull request by spark512**

### CODE REVIEW

**Comment by spark512** [comment]
@IgnacioFDM What about float abs instead of regular abs for integer? There is no need to convert the int to float just to check abs, and then back to float...

**Comment by In-line** [comment]
@spark512 You need to consult a profiler, before optimizations like this

**Comment by IgnacioFDM** [comment]
Yes, I meant fabs. It will be much faster because there is no branching, and it's done in a single FABS instruction (there is an SSE one too I believe). Also it's shorter code, and self explanatory.

**Comment by spark512** [comment]
There is no need for that conversion to int, Q_abs is overloaded and can work with floats directly. Thanks @WPMGPRoSToTeMa.

**Comment by theAsmodai** [comment]
Abs for float faster than for integers.

**Comment by WPMGPRoSToTeMa** [comment]
[Original](https://github.com/ValveSoftware/halflife/blob/5d761709a31ce1e71488f2668321de05f791b405/dlls/func_break.cpp#L599) code is:
```C++
fvol = RANDOM_FLOAT(0.85, 1.0) + (abs(pev->health) / 100.0);
```
But it is compiled with C `abs`, not C++ `abs` which is overloaded for `float`. I think VALVE developers forgot to compile code with C++ `abs`. So we can remove `int` conversions in similar `abs` calls.

**Comment by s1lentq** [comment]
@spark512 Please wrap your the fixed code in the preprocessor REGAMEDLL_FIXES, otherwise it will fail.

**Comment by spark512** [comment]
@s1lentq done

**Pull request merged**
