### PR TITLE
Fix: 'fast fire glitch' at AUG/SG552

### PR DESCRIPTION
**Pull request by RauliTop**
Bug is caused because of not checking weapon's FOV in some conditions.

close https://github.com/s1lentq/ReGameDLL_CS/issues/703

comment from @wopox1337 
> If we keep changing the shared code of weapons for the server side, at some point in time we will get more and more out of sync with the client side (prediction) and this will adversely affect the overall experience of the game for the average player.
> 
> I propose to leave this behavior "as is".

Well, if you don't want to merge it. Let be open to documentation.

### CODE REVIEW

**Comment by Vaqtincha** [comment]
KickBack should also be smaller when the player aimed (fov 55)

**Comment by RauliTop** [comment]
> KickBack should also be smaller when the player aimed (fov 55)

Why? kickback isn't based on FOV

**Comment by Vaqtincha** [comment]
Up

**Review by wopox1337 — APPROVED** [review]
As I said, there are problems with wpn_shared behavior prediction discrepancy, but they only affect clients whose pings are above 70. In general, it's not critical, I think it's possible to make this fix in ReGameDLL.

Video: https://youtu.be/-SLAXhhGwu0
[name](https://youtu.be/-SLAXhhGwu0)

**Comment by wopox1337** [comment]
btw [CS:GO code](https://github.com/perilouswithadollarsign/cstrike15_src/blob/f82112a2388b841d72cb62ca48ab1846dfcc11c8/game/shared/cstrike15/weapon_sg552.cpp#L62-L76):
```cpp

void CWeaponSG552::PrimaryAttack()
{
	CCSPlayer *pPlayer = GetPlayerOwner();
	if ( !pPlayer )
		return;

	bool bZoomed = pPlayer->GetFOV() < pPlayer->GetDefaultFOV();

	float flCycleTime = GetCycleTime();

	if ( bZoomed )
		flCycleTime = 0.135f;

	CSBaseGunFire( flCycleTime, m_weaponMode );
}
```

**Pull request merged**
