### PR TITLE
Initialize m_pevLastInflictor to nullptr to avoid garbage memory

### PR DESCRIPTION
**Pull request by dystopm**
@Nord1cWarr1or

### CODE REVIEW

**Comment by Nord1cWarr1or** [comment]
I will test it

**Comment by dystopm** [comment]
> I will test it

Went good?

**Comment by Nord1cWarr1or** [comment]
@dystopm It seems to be fixed, I don't have any more server crashes, at least not yet

**Comment by dystopm** [comment]
> @dystopm It seems to be fixed, I don't have any more server crashes, at least not yet

Lets take some time. But I'm sure it is related to this.

**Comment by Nord1cWarr1or** [comment]
Still no crash. I think this option really helped

**Comment by dystopm** [comment]
> Still no crash. I think this option really helped

I think we're done with this, @s1lentq

**Pull request merged**
