### PR TITLE
Added new CVar: "mp_block_cmd_drop" - to disable drop cmd from player.

### PR DESCRIPTION
**Pull request by wopox1337**
It need for so many mods and DeathMatch gameplay.

### CODE REVIEW

**Comment by wopox1337** [comment]
tested. Well works now.
image
image

**Comment by wopox1337** [comment]
@WPMGPRoSToTeMa [i added this CVar earlier mp_item_staytime](https://github.com/s1lentq/ReGameDLL_CS/commit/411761c8d885fd521adfb5ac506618ef8846258e). 

Now i added cvar - to block CMD (Command from player).

**Comment by WPMGPRoSToTeMa** [comment]
@wopox1337 `mp_weaponstay` cvar is boolean in HL.

**Comment by WPMGPRoSToTeMa** [comment]
@wopox1337 maybe just `mp_block_drop` or `mp_block_weapon_drop`/`mp_block_item_drop`?

**Comment by wopox1337** [comment]
@WPMGPRoSToTeMa The item can be dropped not only by player cmd but also by death or replacement with other weapons. What makes concrete the meaning of the name

**Comment by WPMGPRoSToTeMa** [comment]
@wopox1337 then maybe something like `mp_block_drop_by_player` or `mp_block_drop_by_player_self`?

**Comment by simosalis** [comment]
Maybe at the same occasion, extend/replace that feature by adding a CVar like "mp_block_cmds", working via flags (abcd...), where each flag allow to block an internal command.
For example, "a" for "say", "b" for "say_team", etc.
There is a limit with that (abcdefghijklmnopqrstuvwxyz), 26 commands, or 32 with the use of extras flags not related to letters ("|" for example) but we can probably regroup some commands to use the same flag (radio1, radio2... linked to one, etc.).

Such addition will give a better control over the default commands available to clients and provided by the game (as blocking the "vote" command, etc.).
Just a suggestion... then it's not long to implement.

**Pull request closed without merging**
