### PR TITLE
Adding new messages for steam beta client.

### PR DESCRIPTION
**Pull request by Karaulov**
Send money and hitpoints to scoreboard.

HalfLife25

_About change visual studio version: I can't work in old visual studio, but after all changes, possible return to old version of Visual Studio._

### CODE REVIEW

**Comment by Karaulov** [comment]
I don't know why one test failed :(

**Comment by Karaulov** [comment]
Now cvars added

**Comment by Mistrick** [comment]
Do you think this is normal to pull commits from another PR? All your past PRs contain commits for VS.
If you port feature from vanilla gamedll you don't need add `REGAMEDLL_ADD`.
What is the point of cvars which still send messages, if it is port from vanilla what is the point do cvar not like in vanilla?
We have messages for health and money and you paste code to functions which update more often than actual update health and money.

**Comment by Karaulov** [comment]
@Mistrick 

> Do you think this is normal to pull commits from another PR? All your past PRs contain commits for VS.
I can't work in old version of Visual Studio, this is impossible!


> If you port feature from vanilla gamedll you don't need add `REGAMEDLL_ADD`.
vanilla gamedll???? what?? i grab it from original cs.so 
and I add all code to REGAMEDLL_ADD because it fail one test in teamcity. 




> We have messages for health and money and you paste code to functions which update not when actual update health and money.

If you disable send money/hitpoints (set mp_scoreboard_showmoney/mp_scoreboard_showhealth "0") ingame, old values be shows in scoreboard.

**Comment by Karaulov** [comment]
@Mistrick, but ok, i add skip send message if cvar not enabled.

**Comment by eat1k** [comment]
It works fine. Could you also add "D. Kit" message when a CT has defuse kit?

image


Moreover, maybe add server CVars? See https://github.com/ValveSoftware/halflife/issues/702#issuecomment-494526399.

> I can't work in old version of Visual Studio, this is impossible!

You've already pull requested it (https://github.com/s1lentq/ReGameDLL_CS/pull/371) so maybe remove it from this PR?

**Comment by voed** [comment]
> 
> I can't work in old version of Visual Studio, this is impossible!


You can revert changes in project files before commiting or fully exclude them from commit.

**Comment by Karaulov** [comment]
@voed I can't use old visual studio. And how to edit pull request? (adding/removing visual studio support every commit? 🤣  )

**Comment by LevShisterov** [comment]
@Karaulov just don,t commit vcxproj and sln files.

**Comment by Karaulov** [comment]
@LevShisterov ??? Add to gitignore ? or how to?

**Comment by Karaulov** [comment]
@LevShisterov I use **GitHub Desktop** to switch between branches and **Visual Studio 2017** for open and edit. 
How to not upload vcxproj and sln files????

**Comment by LevShisterov** [comment]
@Karaulov, I didn't used GitHub Desktop, but all git clients I used had ability to select which files to include in commit. You do not need to add them to ignore. Try to stage (add to index) files you wish to commit before going to commit. Or try TortiseGit for example. Or google "git commit several files".

**Comment by Karaulov** [comment]
GitHub Desktop has 'discard changes' option for files, but I need always edit this files back for support Visual Studio 2017

I close this pull request and wait while this project will be updated to Visual Studio 2017/2019

**Comment by LevShisterov** [comment]
Easy as a pie: [Selecting changes to include in a commit](https://help.github.com/en/desktop/contributing-to-projects/committing-and-reviewing-changes-to-your-project#2-selecting-changes-to-include-in-a-commit)

**Comment by Karaulov** [comment]
```0 don't send any update for this field to any clients
1 send only Terrorist money/health fields to all clients
2 send only CT money/health fields to all clients
3 send Terrorist and CT money/health fields only to members of the same team
4 send Terrorist and CT money/health fields to all clients
```
??? 
For what need 1 and 2 ?

**Comment by eat1k** [comment]
> ```
> 1 send only Terrorist money/health fields to all clients
> 2 send only CT money/health fields to all clients
> 3 send Terrorist and CT money/health fields only to members of the same team
> 4 send Terrorist and CT money/health fields to all clients
> ```
> 
> ???
> For what need 1 and 2 ?

To show money/health only of one team.

**Comment by Karaulov** [comment]
```To update only money/health fields of one team.``` to all client, but for what ? :D

**Comment by eat1k** [comment]
> `To update only money/health fields of one team.` to all client, but for what ? 🤣

I think just for comfort. It was added to original HLDS so it should be added here, too.





> `"D. Kit" message when a CT has defuse kit`, please more info )

In one of the latest beta was also added this text. When someone of CT players buys defuse kit in tab we can see "D. Kit" text.

**Comment by Karaulov** [comment]
@eat1k you can test it? (This is not message, just flag for score attributes)

**Comment by Karaulov** [comment]
@LevShisterov I can't switch between branches if not commit changes of sln/vcxproj files. 

```I close this pull request and wait while this project will be updated to Visual Studio 2017/2019```

**Comment by LevShisterov** [comment]
@Karaulov just do what it suggest: stash changes (sln, vcxproj, whatever), switch branch, unstash. Or use git client that can do that automatically (SmartGit for example). Or search how to do that with your client ([google again](https://github.com/desktop/desktop/issues/1633)).

**Comment by eat1k** [comment]
> @eat1k you can test it? (This is not message, just flag for score attributes)

It works fine.

**Comment by Karaulov** [comment]
@LevShisterov I am not eager to constantly make unnecessary movements: (
I'd rather wait until they update the version of Visual Studio. (maybe 1-5 years :D)

**Comment by WPMGPRoSToTeMa** [comment]
https://stackoverflow.com/questions/653454/how-do-you-make-git-ignore-files-without-using-gitignore

**Comment by Karaulov** [comment]
> https://stackoverflow.com/questions/653454/how-do-you-make-git-ignore-files-without-using-gitignore

> https://stackoverflow.com/questions/653454/how-do-you-make-git-ignore-files-without-using-gitignore

@WPMGPRoSToTeMa I use only Github Desktop client and Visual Studio 2017, and i don't like any additional movements. Probably, someone else will be able to transfer all changes from the Steam client.

**Comment by WPMGPRoSToTeMa** [comment]
@Karaulov that's something you need to do only once, you should already have git because it is required for Github Desktop.

**Comment by Karaulov** [comment]
@WPMGPRoSToTeMa ReGameDLL_CS author already added this messages 😨 🤣

**Comment by MacGyver27** [comment]
I see cvar is not supported in the official latest dev `regamedll-5.7.0.337-dev`, but visually still cant see it in a game..
settings are:
```
mp_scoreboard_showhealth "3"
mp_scoreboard_showmoney "3"
```

Any ideas what I might be doing wrong then? Appreciate any help

**Comment by eat1k** [comment]
> I see cvar is now supported in the official latest dev `regamedll-5.7.0.337-dev`, but visually still cant see it in the game..
> settings are:
> 
> ```
> mp_scoreboard_showhealth "3"
> mp_scoreboard_showmoney "3"
> ```
> 
> Any ideas what I might be doing wrong then? Appreciate any help

You must have the latest beta version of CS 1.6 (8254). If you have it, so create another issue.

**Comment by MacGyver27** [comment]
do I have to compile it myself or are there binaries available ?

**Comment by eat1k** [comment]
> do I have to compile it myself or are there binaries available ?

They're available. You can download [the latest successfull build](http://teamcity.rehlds.org/guestAuth/downloadArtifacts.html?buildTypeId=ReGameDLLCs_Publish&buildId=lastSuccessful).

**Comment by MacGyver27** [comment]
> If you mean ReGameDLL, you can download the latest successfull build. 

Hmm, I am kinda new with this mod. Copied over from the link you sent but still dont see columns HO and Money as in pics above..
> The beta CS 1.6 is available on Steam.
What do you mean by this? Do I have to use different client (game)?

sorry for my lack of knowledge here, thanks for help anyway

**Pull request closed without merging**
