### PR TITLE
Optimize conditional toggle to bitwise operation

### PR DESCRIPTION
**Pull request by In-line**

### CODE REVIEW

**Comment by WPMGPRoSToTeMa** [comment]
Wow, short and beautiful. Maybe add macro `ToggleFlag`?

**Comment by In-line** [comment]
```
#define SetBits(a,b) ( (a) |= (b) )
#define ClearBits(a,b) ( (a) &= ~(b) )
#define IsSetBits(a,b) ( (a) & (b) )
#define InvertBits(a,b) ( (a) ^= (b) )
#define ToggleBits InvertBits
#define IsNotSetBits(a,b) ( ( ~(a) )  & (b) )
```
Why not use something like this?

**Comment by s1lentq** [comment]
@In-line it doesn't violate original logic of the code, you can do without wrapping the macro.

**Comment by In-line** [comment]
@s1lentq i'm just a little macro fun.

**Comment by In-line** [comment]
@s1lentq Are they another places in code where we can do the same trick ? I tried to search but unable to find.

**Comment by s1lentq** [comment]
@In-line [1](https://github.com/s1lentq/ReGameDLL_CS/blob/9b955f2/regamedll/dlls/pathcorner.cpp#L64-L72), [2](https://github.com/s1lentq/ReGameDLL_CS/blob/9b955f2/regamedll/dlls/pathcorner.cpp#L76-L84).

**Pull request merged**
