### PR TITLE
`game_player_equip` checking buggy maps

### PR DESCRIPTION
**Pull request by wopox1337**

### CODE REVIEW

**Comment by Vaqtincha** [comment]
Kolxoz :D

**Comment by Vaqtincha** [comment]
Ya je napisal chto problema v otsutsvii player_weaponstrip (rukajop mapper)

**Comment by Vaqtincha** [comment]
dumayu vrode da vse logichno. no luchshe ubrat eto "HasBuggyMap" i alert i zapixnut etix proverok v "CanEquipOverTouch"

**Comment by Vaqtincha** [comment]
chto kasaetsya aim_deagle ya izuchil ego i tam yest `player_weaponstrip` no pochemu to ne dobavlen v `multi_manager` (koroche mapper nachudil) baga ne bilo bi esli ostavil bi on vot tak (bez svyazki `multi_manager` + `player_weaponstrip`)

{
"origin" "759 -890 -5"
"weapon_knife" "1"
"ammo_50ae" "7"
"weapon_deagle" "1"
"classname" "game_player_equip"
}

ili daje vot tak

{
"origin" "759 -890 -5"
"weapon_knife" "1"
"ammo_50ae" "7"
"weapon_deagle" "1"
"targetname" "game_playerspawn"
"spawnflags" "1"
"classname" "game_player_equip"
}

eto edinochniy sluchay (ved takaye je sistema i v awp_india rabotaet norm)
vot kak ispravit nedokartu aim_deagle odnoy strokoy

Screenshot

**Comment by Vaqtincha** [comment]
Zakrivay pr ne pozorsya. Ya davno dokazal chto problema odnoy karte.

**Comment by hajimura** [comment]
I think its really unnecessary to implement, because the problem occurs a couple maps and fix should be done in the buggy maps, not regamedll

**Pull request closed without merging**
