### PR TITLE
Add member m_iGibDamageThreshold to control GIB damage threshold

### PR DESCRIPTION
**Pull request by dystopm**
The only way to "naturally" GIB on death for players is reaching -9000 health points. This PR adds a CCSPlayer member that controls that value individually per player. It defaults to -9000.

### CODE REVIEW

**Comment by dystopm** [comment]
> The function "CBasePlayer::ShouldGibPlayer" should probably not be in "CSPlayer.h" (more on "player.h"), more due to the fact it is not only "API only feature", due to internal "REGAMEDLL_API" define.

Thing is, I don't know why it doesn't compile when I put this inline function after the CSPlayer method declaration inside player.h - by the way, @s1lentq implemented the `DmgPenetrationLevel` methods in CSEntity.h (#858) when their declarations are on cbase.h and I guess it's because the same compilaton (also did the same in (#896).

**Comment by StevenKal** [comment]
Maybe putting it inside the "#ifdef REGAMEDLL_API" on "player.h" line 953 could skip the compiler error, then a #else with duplicated function without the member.
However, a non-inline function, but does not worth to expose such tiny check.

**Comment by dystopm** [comment]
> Maybe putting it inside the "#ifdef REGAMEDLL_API" on "player.h" line 953 could skip the compiler error, then a #else with duplicated function without the member. However, a non-inline function, but does not worth to expose such tiny check function.

```c++
#ifdef REGAMEDLL_API
inline CCSPlayer *CBasePlayer::CSPlayer() const {
	return reinterpret_cast<CCSPlayer *>(this->m_pEntity);
}
#endif
inline bool CBasePlayer::ShouldGibPlayer(int iGib)
{
#ifdef REGAMEDLL_API
	int threshold = CSPlayer()->m_iGibDamageThreshold;
#else 
	int threshold = GIB_PLAYER_THRESHOLD;
#endif
	return ((pev->health < threshold && iGib != GIB_NEVER) || iGib == GIB_ALWAYS);
}
```
It wont compile 💀 am I forgetting something?

**Comment by StevenKal** [comment]
I was thinked to more something like:
```
#ifdef REGAMEDLL_API
inline CCSPlayer *CBasePlayer::CSPlayer() const {
	return reinterpret_cast<CCSPlayer *>(this->m_pEntity);
}

inline bool CBasePlayer::ShouldGibPlayer(int iGib)
{
	return ((pev->health < CSPlayer()->m_iGibDamageThreshold && iGib != GIB_NEVER) || iGib == GIB_ALWAYS);
}
#else
inline bool CBasePlayer::ShouldGibPlayer(int iGib)
{
	return ((pev->health < GIB_PLAYER_THRESHOLD&& iGib != GIB_NEVER) || iGib == GIB_ALWAYS);
}
#endif
```

But might not compile too!

**Comment by dystopm** [comment]
> I was thinking to more something like:
> 
> ```c++
> #ifdef REGAMEDLL_API
> inline CCSPlayer *CBasePlayer::CSPlayer() const {
> 	return reinterpret_cast<CCSPlayer *>(this->m_pEntity);
> }
> 
> inline bool CBasePlayer::ShouldGibPlayer(int iGib)
> {
> 	return ((pev->health < CSPlayer()->m_iGibDamageThreshold && iGib != GIB_NEVER) || iGib == GIB_ALWAYS);
> }
> #else
> inline bool CBasePlayer::ShouldGibPlayer(int iGib)
> {
> 	return ((pev->health < GIB_PLAYER_THRESHOLD&& iGib != GIB_NEVER) || iGib == GIB_ALWAYS);
> }
> #endif
> ```
> 
> But might not compile too!

It wont recognize CSPlayer method, and I don't know why, it's getting defined above (lol). Some cpp coder may elaborate on this, I'm still a rookie :)

**Pull request merged**
