### PR TITLE
completly disable buyzone when mp_buytime is 0

### PR DESCRIPTION
**Pull request by justgo97**
currently when you set mp_buytime 0 it shows buyicon and its allows you to open weapons menu and when you try buy somthing it show "0 seconds passed since..." now with this patch no icon will be shown and menu will not open.

### CODE REVIEW

**Comment by Phantomsq** [comment]
I think, these changes must be in REGAMEDLL_FIXES

**Comment by justgo97** [comment]
> I think, these changes must be in REGAMEDLL_FIXES define

its not a bug older hlds didn't have this option.

**Comment by Phantomsq** [comment]
Isn't it logically that if we will set 0 to this cvar, buyzone must be disabled without showing buyicon and message:

> "0 seconds passed since..."

I still think, that it's FIXES

**Comment by justgo97** [comment]
old gamedll doesn't allow value less then 0.25 with regamedll there is two new options -1 = unlimited time and 0 = disabled. so its new features more then a fix or mayby fix for a features, REGAMEDLL_FIXES should be used only for a bug that was in engine and it got fixed which is not the case here.

**Comment by Phantomsq** [comment]
Dunno, anyway imo this is fix

**Comment by justgo97** [comment]
yes you can call it a fix but its not the fix that should be under REGAMEDLL_FIXES.

**Comment by Phantomsq** [comment]
Ok

**Comment by justgo97** [comment]
> Ok, as you want

its not as i want it how it i think it should be.

**Pull request merged**
