### PR TITLE
Add an extended player's DeathMsg message

### PR DESCRIPTION
**Pull request by s1lentq**
**Description**
These changes introduces enhancements to the DeathNotice function,
providing extra death flags to convey more information in death messages.
These flags are used to include extra details about player deaths, making death messages more informative

- Extra Death Flags:

  - PLAYERDEATH_POSITION (Bit 1):
    Position of Victim's Death: This flag includes the coordinates (X, Y, Z) of the place where the victim died.
    It is useful for displaying a 'dead icon' on the HUD radar, indicating the victim's death location.

  - PLAYERDEATH_ASSISTANT (Bit 2):
    Index of Assistant: When set, this flag includes the index of the assisting player who helped the attacker kill the victim. It allows players to know who assisted in the kill.

  - PLAYERDEATH_KILLRARITY (Bit 4):
    Kill Rarity Classification: This flag adds a rarity classification to the death message.
    It includes information about the rarity of the kill, such as headshot kills, kills through walls, flash assists, and more.
    These classifications make death messages more engaging by highlighting exceptional kills.

    - Headshot Kill: Indicates that the victim was killed by a headshot, signifying exceptional accuracy and precision.

    - No-Scope Kill: Denotes a kill with a sniper rifle without using the scope, showcasing remarkable skill and reflexes.

    - Penetrated Kill: Highlights kills made through walls or objects, demonstrating tactical prowess.

    - Flash Assist: Marks kills assisted by flashbang grenades, revealing coordinated teamwork.

    - And More: Additional classifications may be introduced to further enrich the gameplay experience.

**Usage for Developers:**
AMXX plugin developers can use these flags to extract valuable information, such as kill rarity and other details, for use in their plugins.
Functions like hookchain CSGameRules_SendDeathMessage, register_message and register_event can be employed to access this additional information. 

**Benefits client-side for unofficial clients:**
These enhancements extend beyond the official game, but it can benefit unofficial game clients as well. Non-official clients can use this additional information to create visual enhancements and customizations. This allows for a richer gaming experience and increased player engagement.

### CODE REVIEW

**Comment by wopox1337** [comment]
With this code for improved game clients get to do something like this:
image

**Comment by q52888940** [comment]
Don't need an spr?

**Comment by axl303** [comment]
Should we see the assist nickname or something in the DeathMsg? Assuming pAssister?
https://github.com/s1lentq/ReGameDLL_CS/blob/3df37bd2f8d13f12bb1f763985b31ddffced6551/regamedll/dlls/multiplay_gamerules.cpp#L4165
Example: Player1 + Player2 > killed Player3
Tested with "mp_assist_damage_threshold (def) 40, also with 10" and I don't see a KillAssist name in DeathMsg
Also with mp_deathmsg_flags 1-7 (2) and still nothing.

Sorry for the stupid question, but I don't get it 😅

**Comment by q52888940** [comment]
Do you support zbot?

**Comment by Nord1cWarr1or** [comment]
> Should we see the assist nickname or something in the DeathMsg? Assuming pAssister?
> 
> https://github.com/s1lentq/ReGameDLL_CS/blob/3df37bd2f8d13f12bb1f763985b31ddffced6551/regamedll/dlls/multiplay_gamerules.cpp#L4165
> 
> Example: Player1 + Player2 > killed Player3
> Tested with "mp_assist_damage_threshold (def) 40, also with 10" and I don't see a KillAssist name in DeathMsg
> Also with mp_deathmsg_flags 1-7 (2) and still nothing.
> 
> Sorry for the stupid question, but I don't get it 😅

Have you read the above text?

> AMXX plugin developers can use these flags to extract valuable information, such as kill rarity and other details, for use in their plugins.
Functions like register_message and register_event can be employed to access this additional information.

**Comment by StevenKal** [comment]
Since when those extras "DeathMsg" features are implemented on the client?

**Comment by SmileYzn** [comment]
> Good feature. But, since when those extras "DeathMsg" features/parameters have been implemented on the client?

NEVER!

**Comment by wopox1337** [comment]
> But, since when those extras "DeathMsg" features/parameters have been implemented on the client?

@StevenKal You can implement this on your client if you practice. The standard vanilla client does not have these features.

**Comment by StevenKal** [comment]
O.K., I supposed this had been implemented on a client update I was not aware of, that's why s1lentq added such but in fact he just extended so we can retrieve those infos via plugins, nothing more.

**Comment by FEDERICOMB96** [comment]
Nice!
I have one more suggestion. You can also add "domination/revenge" as part of "kill rarity".

Example video
[https://www.youtube.com/watch?v=cnMWoupwH6s](url)

**Pull request merged**
