### PR TITLE
Make Knife back stab multiplier customizable

### PR DESCRIPTION
**Pull request by dystopm**
*title*

Feature addition, plus a few line changes, up to modders preferences.

### CODE REVIEW

**Comment by StevenKal** [comment]
"*iplier"!

**Comment by PM32** [comment]
> Write the whole word ("*iplier")! + Add the define "REGAMEDLL_ADD".

Thanks you for your observation. I did not add the REGAMEDLL_ADD macro because the written CKnife modification members, the ones preceded by m_flStab/m_flSwing, were not programmed under the above clauses, so I did a wild guess by just extending it. That should be reviewed by the repo maintainers. What do you think?

About the Mult suffix, it is between unnecessary but sane, so I'll wait for someones commentary about it. If you have anything else to add I'll be glad to see it.

**Comment by StevenKal** [comment]
> > Thanks you for your observation. I did not add the REGAMEDLL_ADD macro because the written CKnife modification members, the ones preceded by m_flStab/m_flSwing, were not programmed under the above clauses, so I did a wild guess by just extending it. That should be reviewed by the repo maintainers. What do you think?

Yeah knowing this maybe it can be skipped & so not added, or, added from "m_flStabBaseDamage" if they decide to.

> > About the Mult suffix, it is between unnecessary but sane, so I'll wait for someones commentary about it. If you have anything else to add I'll be glad to see it.

I recommend it, a proper & complete name does not hurt!

**Comment by dystopm** [comment]
> Write the whole word ("*iplier")! + Add the define "REGAMEDLL_ADD".

I ended adding what you wrote here :) 

@s1lentq some sort of possibility to check this out, and some future ones? Got time for editing and extending this repo

**Comment by RauliTop** [comment]
Do we need that new members added to include?? @dystopm

**Comment by dystopm** [comment]
> @dystopm Do we need to add these new members on ReAPI include??

Thing is, ReAPI module should be edited and add the last member added to the member table, it isn't enough with editing the include. In other hand, Minor version should be updated in both ReGameDLL and ReAPI, so you can track changes correctly.  There are plenty of API upgrades as pull requests so it depends of repo maintainers to merge one of these and update minor version, forcing ReAPI to be updated also.

**Pull request merged**
