### PR TITLE
Add mp_max_intermission_time cvar

### PR DESCRIPTION
**Pull request by In-line**
Basically this gives opportunity to change intermission behavior for server administrators. Imagine situation when 32 noobs are not pressing any key and shouting that map change is going too long.

Credits (for idea)
- @wopox1337
- @Fant1kUA

### CODE REVIEW

**Comment by WPMGPRoSToTeMa** [comment]
Why do we need a new cvar? Administrators can't control `mp_chattime`?

**Comment by In-line** [comment]
When I faced this problem, I thought like this:
1. Intermission before map change is common behavior for a long time.
2. There is gonna be some addon developer, that relied on this behavior.
3. Same as 2, but for players that love intermission.

So it is better to leave a decision to the server administrator. I will add additional check to block SVC_INTERMISSION if mp_max_intermission_time is zero.

**Comment by WPMGPRoSToTeMa** [comment]
@In-line may be better add `mp_intermission_auto_end` or something like this?

**Comment by In-line** [comment]
@WPMGPRoSToTeMa I don't think that it's necessary, but if somebody else support that idea I see no reason for resistance :)
I think it will complicate things, if somebody wants `SVC_INTERMISSION` with 0 timeout, he or she can just set `mp_max_intermission_time` to `0.0001`

**Pull request closed without merging**
