### PR TITLE
Implement `CBasePlayer::Observer_SetMode` hook

### PR DESCRIPTION
**Pull request by Lopol2010**
related issue s1lentq/reapi#207

### CODE REVIEW

**Comment by StevenKal** [comment]
Value of "GetForceCamera" hook could possibly overwrite your custom mode, and if set to "CAMERA_MODE_SPEC_ONLY_FIRST_PERSON" (2) eye camera will be set internally.

**Comment by Lopol2010** [comment]
Hi it seems in my server spectator restrictions work fine. Also i think if you have problems then you can set GetForceCamera return to any values?

**Comment by StevenKal** [comment]
This can be pushed too (with adjustements regarding other hooks of fl0werD, or keep v5.21 and merge all [4 hooks] at once).

**Comment by Lopol2010** [comment]
@StevenKal, Are you talk to me? If so, do you mean i need to resolve conflicts?

**Comment by hajimura** [comment]
I think conflicts should be fixed anyway

**Comment by StevenKal** [comment]
I was just refering to the "5.21" version upgrade, but I think while the maintainer/collaborators do not push a release in the "Releases" branch but keep adding/merging some new API functions, your hook could keep "5.21" as version and be added after fl0werD's hooks recently added (other API functions could even be added at same time and keep same version), no need to push to 5.22.

**Review by wopox1337 — APPROVED** [review]

**Pull request merged**
