### PR TITLE
Implement `CGib::SpawnHeadGib` and `CGib::SpawnRandomGibs`

### PR DESCRIPTION
**Pull request by FEDERICOMB96**
related https://github.com/s1lentq/reapi/pull/200

### CODE REVIEW

**Review by wopox1337 — APPROVED** [review]

**Review by wopox1337 — APPROVED** [review]

**Comment by Vaqtincha** [comment]
It's useless. Any entity can be created using rg_create_entity.

**Comment by Vaqtincha** [comment]
Then let's create natives for each entity. rg_create_defuser rg_create_hostage rg_create_weaponbox ...

**Comment by metita** [comment]
Not sure if you are serious or not but did you even tried to do what are you implying? Based on what you say there are plenty of things that are implemented on ReAPI that can be done through members, entvars or create_entity, you are not forced to use these natives but then stick to your own methods, things like these makes programming easier for the end user.

**Comment by Vaqtincha** [comment]
No need for rubbish api with unnecessary natives.

That's why today's programmers are so lazy.

**Comment by metita** [comment]
Your argument is pretty vague honestly, again, based on your statement just keep RegisterHookChain/set/get_entvar and set/get_member and just let people do their job in a hard way? Maybe you should go and google what is a Framework or how libraries/API works, maybe you will notice a common pattern which is making programmer life easier, by the way not everyone is cappable of making a functional code even with everything ready or how to use on their respective docs.

https://github.com/s1lentq/ReGameDLL_CS/pull/636 this is easily programmable.
https://github.com/s1lentq/ReGameDLL_CS/pull/621 You can add StatusIcon too via AMXX :)
https://github.com/s1lentq/ReGameDLL_CS/pull/555 Hey this can be made too!
https://github.com/s1lentq/ReGameDLL_CS/pull/539 Does not ReAPI has a hook for falldamage? Or I am wrong?
https://github.com/s1lentq/ReGameDLL_CS/pull/600 You seems to be a crybaby, noticed some pattern there too, don't give up))
https://github.com/s1lentq/ReGameDLL_CS/pull/454 ^

**Comment by Vaqtincha** [comment]
Absolutely wrong comparison. It looks like you yourself do not know what api is. Try to do something first

**Comment by Vaqtincha** [comment]
"#555 Hey this can be made too!"

you won't do it.

all my commits are made to exclude amxmod dependency.

**Comment by Vaqtincha** [comment]
your api is only needed for one plugin. don't be smart here

**Comment by Vaqtincha** [comment]
Ясно с размышлением оленей.
Этих ты
https://github.com/s1lentq/ReGameDLL_CS/pull/636
https://github.com/s1lentq/ReGameDLL_CS/pull/555
https://github.com/s1lentq/ReGameDLL_CS/pull/600
фиг программируешь.

Да видел ваших костылей на оленах. А мой работает сто роз лучше чем у вас.
Спор окончен!

**Comment by metita** [comment]
In fact I do not need anything from ReAPI/ReGameDLL because it already offers what I need.

Uhm yeah, making random spawns is pretty easy through AMXX, I am not trying to be smart or anything, just making a point on your argument (can be considered as that? seems just a complain for nothing), you have good pull request and issues, not gonna lie, but your statement regarding this one just make nonsense, please, take a look at ReGameDLL and ReAPI main page, pull request are welcomed and are presented as a powerful and extended API for mods/plugins.

ReGameDLL goals:
> Provide more stable (than official) version of Counter-Strike game with extended API for mods and plugins
...
> Merge requests are also welcome 

Instead of not adding content just because it it useless (?), if you do not need it, just do not use it, more people will find it useful and whoever has a use will be grateful for this implementation rather than searching for a workarounds.

**Comment by Vaqtincha** [comment]
@metita I will not argue with a fool. good luck

**Comment by metita** [comment]
By the way, I tried to have a good discussion with you but looks like I was not wrong at all with your attitude, sadly.
Maybe try to search how I have contributed to the game (half-life repo), but that's not how it works, at the end just s1lent have the final word 👍

**Comment by metita** [comment]
> "#555 Hey this can be made too!"
> 
> you won't do it.
> 
> all my commits are made to exclude amxmod dependency.

Hey! Guess what! this is made to exclude AMXMODX dependancy too!!

**Comment by Vaqtincha** [comment]
"Uhm yeah, making random spawns is pretty easy through AMXX"

show me at least one normal random generator. you have no idea how it works.

**Comment by fl0werD** [comment]
> That's why today's programmers are so lazy.
Yes, how dare they make their job easier!

**Comment by StevenKal** [comment]
"#600 You seems to be a crybaby, noticed some pattern there too, don't give up))"

I love that! Hehehe!
Yeah, please do not give up! Or just push that #600 as it is, this will be at least better than "nothing"!

**Review by wopox1337 — APPROVED** [review]

**Pull request merged**
