### PR TITLE
Fix `m_flAccuracy` calculation

### PR DESCRIPTION
**Pull request by wopox1337**
Fixes and improves smooth spread transitions when shooting automatic weapons.
🤌

### CODE REVIEW

**Comment by wopox1337** [comment]
@StevenKal What do you think about this PR 🧐?

**Comment by hajimura** [comment]
shedevr

**Comment by TibyXD** [comment]
Related to Fix Accuracy plugin by MPNumB?

**Review by hajimura — APPROVED** [review]

**Comment by StevenKal** [comment]
Haha cute wopox, sounds like you want to keep me reactive or have fun with me! Hehehehehe!
And you, what do you think about my module [ReAPI](https://www.amxmod.net/forum/showthread.php?tid=1522)?!!! Hihihi!

I only see the usage of some #define rather than hardcoded numbers, well, just for the sake of "making the things clean" (readability...), there are PRs much more interesting than that! Come on I know you can submit more interesting! Hihihi!

**Comment by wopox1337** [comment]
> Come on I know you can submit more interesting! Hihihi!
From that moment on, my interest was gone. Thank you. 👍

**Comment by hajimura** [comment]
> 
> I only see the usage of some #define rather than hardcoded numbers, well, just for the sake of "making the things clean" (readability...), there are PRs much more interesting than that!
The PR fixes wrong m_flAccuracy calculation of weapons. Due this time there was a math data loss that was fixed by this code

**Comment by StevenKal** [comment]
"Come on, I know you can be more considerate and serious."

Show the good example in first!

**Pull request merged**
