### PR TITLE
Revert wpn_elite cycletime fix

### PR DESCRIPTION
**Pull request by voed**
Explained here https://github.com/s1lentq/ReGameDLL_CS/issues/3#issuecomment-558133236

### CODE REVIEW

**Comment by satnatantas** [comment]
This weapon is almost never used, it is next to impossible to control it at higher firing rate, and the bullet marks are not even correct with cl_lw 0 on any server and it has parallax unlike any other weapon. Please do not ruin the only fun weapon who nobody uses.

https://github.com/ValveSoftware/halflife/issues/2822

**Review by wopox1337 — COMMENTED** [review]
nope

**Comment by wopox1337** [comment]
a

**Comment by wopox1337** [comment]
I think at the moment ReGameDLL has a normal shooting speed, at least based on CS:GO (which is supported by Valve).

Video: https://youtu.be/w5fJrNsYa-U
[name](https://youtu.be/w5fJrNsYa-U)

**Pull request closed without merging**
