### PR TITLE
Fix Ammo on drop gun

### PR DESCRIPTION
**Pull request by scripting6**
Hi,
I have AutoMix server - looking for fix ammo when player take a weapon from another player / from bot
if BOT buy deagle and another player take control of the bot he got deagle with 7 bullets without ammo
same as if I drop deagle to my friend - when I have 35 ammo and when the friend take the deagle he will 7 bullets without ammo

### CODE REVIEW

**Comment by Vaqtincha** [comment]
https://github.com/s1lentq/ReGameDLL_CS/issues/520
https://github.com/s1lentq/ReGameDLL_CS/issues/620

Ps not a bug

**Comment by scripting6** [comment]
> #520 #620
> 
> Ps not a bug

what is mean?

**Comment by scripting6** [comment]
> #520 #620
> 
> Ps not a bug

RegisterHookChain(RG_CreateWeaponBox, "CreateWeaponBox")
isn't work

**Comment by scripting6** [comment]
fixed it, Thanks.

**Comment by dystopm** [comment]
@wopox1337 you can consider closing this in response of #840 merge

**Pull request closed without merging**
