### PR TITLE
Added Hookchain for CBotManager::OnEvent

### PR DESCRIPTION
**Pull request by SmileYzn**
Added Hookchain for CBotManager::OnEvent

### CODE REVIEW

**Comment by SmileYzn** [comment]
Is needed to update CSSDK?
I guess that regamedll_api.h will need to include GameEvent.h

**Comment by SmileYzn** [comment]
@wopox1337 

Any date to merge with master?

**Comment by StevenKal** [comment]
~1 year of delay!

**Comment by SmileYzn** [comment]
> ~1 year of delay!

I really did not understand why distinguish pull requests, maybe create an fork anyway.

**Comment by StevenKal** [comment]
Well, if you need call or hook things "in emergency", just use memhack stuff until API with your needs is pushed.

**Comment by s1lentq** [comment]
Done #849

**Pull request closed without merging**
