### PR TITLE
Fix teleport players to invalid spawn points

### PR DESCRIPTION
**Pull request by hajimura**
Resolves https://dev-cs.ru/threads/1056/post-121514

### CODE REVIEW

**Comment by RauliTop** [comment]
Will this cause a player in a server with semiclip can't teleport if another player at teleport spawn?

**Comment by hajimura** [comment]
> Also, disabling mp_kill_filled_spawn makes all spawn points valids

So, i could add third bool parameter to IsSpawnPointValid func check or not this cvar

**Comment by RauliTop** [comment]
What about first question?

**Comment by StevenKal** [comment]
> What about first question?

Except when "mp_kill_filled_spawn" is "0", the "IsSpawnPointValid" simply searches if there is an entity in the sphere of the spawn, with 64 units max range, so, if another player is found, it will return false without taking care of the collisions properties set via semiclip plugins...
The modified code submitted simply prevents the teleport in case of the spawn "IsSpawnPointValid" returns false, rather than teleporting no matter what (so possibly on an invalid location [but should not be the case when destination's origin properly set], or, if there is already a client on the destination, as example).
But to handle better teleport on spawn & third-party plugins as semiclip, some other modifications will be required.
We could even start using "UTIL_EntitiesInBox" or even the unused "UTIL_IsSpawnPointOccupied" function, witch checks for boxes instead of sphere, a player has vertical rectangular boxes so it will make sense to use such, with a few modifications.
We could even add some kind of "UTIL_UnstuckClient" & use it at some places like for info_teleport_destination (hum, because two players who use the entry at the suite gonna spawn & do deep hugs!). But this code will prevent the second player to hug the first, till the first not moved around...

**Comment by Vaqtincha** [comment]
Why?

**Comment by hajimura** [comment]
Its unnecessary, because not gonna be merged 🚢


> Will this cause a player (in a server with semiclip) can't teleport if another player is at teleport spawn?

Yes

**Pull request closed without merging**
