### PR TITLE
New entity `trigger_bomb_reset`

### PR DESCRIPTION
**Pull request by wopox1337**
Description: https://developer.valvesoftware.com/wiki/Trigger_bomb_reset

- [x] Implement entity `trigger_bomb_reset`;
- [x] Implement bomb touch logic;
- [x] Implement bomb position save \ restore logic;
- [x] Add `trigger_bomb_reset` to `.fgd`.

Video:
https://youtu.be/RqTGX3efPZE
[name](https://youtu.be/RqTGX3efPZE)

Test map:
[35_hp2 (trigger_bomb_reset).zip](https://github.com/s1lentq/ReGameDLL_CS/files/10195902/35_hp2.trigger_bomb_reset.zip)

### CODE REVIEW

**Comment by abecee** [comment]
Hi. This will block the bmb stuck on mirage in t spawn and nuke under the t spawn truck? @wopox1337

**Comment by wopox1337** [comment]
> Hi. This will block the bmb stuck on mirage in t spawn and nuke under the t spawn truck? @wopox1337

It is necessary to create a package of plugins, with the addition of these entities. (or create them with AMXModX plugins)

**Comment by abecee** [comment]
> > Hi. This will block the bmb stuck on mirage in t spawn and nuke under the t spawn truck? @wopox1337
> 
> You need to create a pack of maps, with the addition of these entities. (or create them with AMXModX plugins).
> 
> Yes, this is created for this purpose.

Oki, ty.

**Comment by StevenKal** [comment]
Should not it be in the folder "addons"?

**Pull request merged**
