### PR TITLE
new cvar `mp_smoke_thickness`

### PR DESCRIPTION
**Pull request by yuyiken**
[](url)With this cvar you can make smoke effect thicker when smoke grenade explodes. 

Up to 5 smoke grenade. 

Idea was taken from [this](https://pastebin.com/aZXXZbiP) plugin.

[Video](https://www.youtube.com/watch?v=Bn2IeKWDrpc).

### CODE REVIEW

**Comment by Escap3d** [comment]
anti smoke file download included

**Comment by yuyiken** [comment]
> anti smoke file download included

what do you mean with antismoke?

**Comment by abecee** [comment]
> anti smoke file download included 

The link doesn't work.

**Comment by Escap3d** [comment]
> > anti smoke file download included
> 
> 
> 
> what do you mean with antismoke? 

Some players are delete smoke puff sprite file delete then join tha server

**Comment by yuyiken** [comment]
> > > anti smoke file download included
> > 
> > 
> > what do you mean with antismoke?
> 
> Some players are delete smoke puff sprite file delete then join tha server

Of course, you can check user files with rechecker?

**Comment by Escap3d** [comment]
> > > > anti smoke file download included
> > > 
> > > 
> > > what do you mean with antismoke?
> > 
> > 
> > Some players are delete smoke puff sprite file delete then join tha server
> 
> Of course, you can check user files with rechecker?

Rechecker not detected smoke ka

> > > > anti smoke file download included
> > > 
> > > 
> > > what do you mean with antismoke?
> > 
> > 
> > Some players are delete smoke puff sprite file delete then join tha server
> 
> Of course, you can check user files with rechecker?

Rechecker is on and use, but the smoke file gets deleted

**Comment by Nord1cWarr1or** [comment]
> > Some players are delete smoke puff sprite file delete then join tha server
> 
> Of course, you can check user files with rechecker?

Rechecker can be bypassed

**Comment by abecee** [comment]
Hi. I wanna add something. I've tested the smoke plugin and i've found a bug. Sometimes i can see the name of the player that i'm aiming through smoke. If u want to add this into regame, u have to fix this or is useless.

**Comment by yuyiken** [comment]
> Hi. I wanna add something. I've tested the smoke plugin and i've found a bug. Sometimes i can see the name of the player that i'm aiming through smoke. If u want to add this into regame, u have to fix this or is useless.

Hi, yesterday, I was testing related to name stuff, I still need learn a lot about c++ and regamedll, but some conclusions I got. with any smoke from 1 to n, there are some angles that will always show name. When I tried to disable name, the effect only take on next round. I decided to remove enemy's name but it looks very strange..  All we are used to see enemy names and removing it will be annoying, so I won't implement this for now. I'm looking for another solution.

**Comment by abecee** [comment]
> > Hi. I wanna add something. I've tested the smoke plugin and i've found a bug. Sometimes i can see the name of the player that i'm aiming through smoke. If u want to add this into regame, u have to fix this or is useless.
> 
> Hi, yesterday, I was testing related to name stuff, I still need learn a lot about c++ and regamedll, but some conclusions I got. with any smoke from 1 to n, there are some angles that will always show name. When I tried to disable name, the effect only take on next round. I decided to remove enemy's name but it looks very strange..  All we are used to see enemy names and removing it will be annoying, so I won't implement this for now. I'm looking for another solution.

Hi. You can hide the name when a smoke is in front of you or close to you. That's the only solution you've got. Maybe someone can help you with that, i don't know. Removing that is not a solution because it is like you said, it's weird, we all are used to seeing names.

**Comment by yuyiken** [comment]
> I did not know how to explain, but also has other bug with smoke. The sprites never touch the ground, i think that sprites are fired when smoke explode with 1px from floor to sprite, so players can see through smokes.
> 
> It looks like CS 1.6 train wall bug, but for smoke sprites.
> 
> https://www.youtube.com/watch?v=vtPclNDXZuI

Thank you, I will check later

**Pull request closed without merging**
