### PR TITLE
Fix player's velocity on pushable use

### PR DESCRIPTION
**Pull request by voed**
More info in #347, i've broken that pr @_@

### CODE REVIEW

**Comment by WPMGPRoSToTeMa** [comment]
Cvar???

**Comment by voed** [comment]
@s1lentq decided that cvar is unnecessary

**Comment by Karaulov** [comment]
@voed On all maps it used as is, with bug. Only new maps can use this fix. Possible need add cvar to enable this bug again?

**Comment by voed** [comment]
> On all maps it used as is, with bug

No, its not.

**Comment by Karaulov** [comment]
> No, its not.

When this bug has been added?

**Pull request merged**
