### PR TITLE
push

### PR DESCRIPTION
**Pull request by afwn90cj93201nixr2e1re**

### CODE REVIEW

**Comment by StevenKal** [comment]
Finally someone takes time to add those useful functions! Thanks.
But please try adding a title or/and description for future things! At least people quickly know what this is about instead of moving to files details, despite it is not much dramatic and people like me will probably look at the details (since titles do not contain frequently all of the changes & additions).
PS: If you have time for it, could you add an "ED_Free" hook for ReHLDS? Do not ask me to do it however I will not ask you to do it so!

**Comment by StevenKal** [comment]
I do not really get why you are saying "we shouldn't use pull requests to track change history", while this is not that I was refering to. Pull requests are like "submissions of modifications", I personnaly never used that to track changes history, those are "unofficial/dormant" changes until they got accepted & moved to the project, like on my own version of the ReAPI module, I have tracked all the "final commits" of both ReHLDS & ReGameDLL_CS project to figure out which version was required per function & hook, but certainely not the "Pull requests" parts!
By the way, those projects really lack a "proper changelog" (or two, one for changes/additions, another one for "API things" only) for users!

But that I am refering here, in my first comment, is about the "push" you write as title, you take time to write "codes" in your pull requests, but can not write something like "API: Add "CBaseEntity::Fire<Bullets[3]|Buckshots> hooks."? This will inform people about what your PR contain, make the PR more "clean" and would not hurt huh! And if at worse there are more things than that, add a " & extras" after".
As I previously said, it is not much dramatic, but this is for the visual readability (and information) of other people.
Also, I can give you an example why it can be preferable, let's imagine you make multiple PRs named "push", first, people might be lost among them (to search back one precise [because the #* are just not informative at all huh], etc.), secondly, if we check one or two of you, and, on those two you have just made basic cosmetic changes that do not matter much to people (like "we do not care, those are trivial things"), well, after that people like me may not likely return to check your future PRs, while, those futures ones could be something else than "just cosmetic changes" (like now, new API additions being more interesting!!).
And, at the end, more the people will check your PRs, more you might have chances to see them "thank you" (like I did), or even better, submit suggestions to you, or even modifications/additions, in order to enhance the final PR s1lentq will approve (so, more "contributions" from others).
By the way, in all the ReGameDLL_CS's PRs, you are almost the only one who does not write a standard clean description ("push", "test", etc.). Those PRs are not private so you could try make some efforts please!!

It is not I want to looking for troubles with you (not my intention), it is just I think this is selfishness and idleness, just like when some comments on those projects repositories have been written in Russian, you told me once this was "our private conversation that does not concern others", while I remember translated them via Google and they did not appear "much private" to me, but informative for the others not talking Russian, it is just like if on an English forum topic, you suddently started to write in Russian (while you can in English), this is not much respectful to me, and here this is similar, so English should be used for any comment, hehehe!

**Comment by afwn90cj93201nixr2e1re** [comment]
.

**Comment by afwn90cj93201nixr2e1re** [comment]
.

**Comment by StevenKal** [comment]
Well, a lot of "lambda users" use & also follow those projects, even knowing most of them do not know programming (as I said, they are lambda users who use stuff, not code such plugins, modules, etc., and I know a lot of AMX users who do not even know how to compile plugins, so what about C++ stuff! All lost!). But some of those non-programmers users like to follow that's happening, and take a look at issues & PRs, at least for curiosity. So for me, one more reason to use eloquent title on those!

Well, if as you say, Russians or non-Russians developers do not understand that's happenning, this is critical, because either they do not follow well the projects and are not aware of that's happenning (like when you take a look by curiosity on a program's repository you are not aware of), or, either they are not programmers (or at least not C++ ones) if they can not understand the kind of code on those Re* projects.
Game(s) code (most of the HL1 engine based ones) is in my opinion not much complicated to understand, but the engine's one is more complex (at least various parts) and also a bit in mess, I personnaly do not understand some blocks or I am lazy to try.

"I still can't understand what we're talking about now, about PR or about commits."
-> I was only refering about "specify a clean title description for a PR (or issue)", instead of writting just "push", nothing more! But I have the feeling you misunderstood me, because when I read you it seems you have diverged a bit from the exact thing I wanted to point out. Well, not much dramatic, at least you gave me details of third-party things! Hehe!

By the way, I see that the PR is closed, I hope it is not "abandonned" or "refused" (despite I saw some closed PRs being granted to the final project), because I remember Asmodai saying something like "it was bad to hook FireBullets, etc.", so I hope s1lentq will not refuse such hook addition, it will be so stupid in my opinion, because if devs claim their hook system is better than memhack, but still refuse to add such hooks "for the stupid addiction of the drugged people about the high performance", knowing nowadays the machines are much more powerful than the past and can handle such hooks without much problem, it will be pathetic, and I do not see how much is the point to code an internal enhanced hooking system if it's not to use it for all of that we want...

**Pull request closed without merging**
