### PR TITLE
remove buggy immunity status icon

### PR DESCRIPTION
**Pull request by Vaqtincha**

### CODE REVIEW

**Comment by Vaqtincha** [comment]
Тестируйте хорошенько и не принимайте пр сразу. Лет где-то 3-4 надо тестировать.

**Comment by StevenKal** [comment]
That shield icon for "protection" is not bad, and if the #695 solves the issue of it which keeps blinking after the end when it should not, just use it instead or remove it.

**Comment by Vaqtincha** [comment]
@StevenKal No. I've only done bad things for cs.

**Comment by StevenKal** [comment]
I am so sorry to disturb you in your "bad things work"! Hehehehehe!

**Comment by Vaqtincha** [comment]
Pofig togda. 😁

**Pull request closed without merging**
