### PR TITLE
Fix semiclip player names (thanks to StevenKal)

### PR DESCRIPTION
**Pull request by RauliTop**
Discussed here: https://github.com/s1lentq/ReGameDLL_CS/issues/732

credits to @StevenKal

### CODE REVIEW

**Comment by RauliTop** [comment]
Build should be fixed now @wopox1337

**Comment by hajimura** [comment]
wtf

**Comment by wopox1337** [comment]
these problems are related to the third-party module semiclip, not regamedll

**Comment by StevenKal** [comment]
Rauli, seems like you gonna keep using [this](https://github.com/StevenKal/ReGameDLL_CS/releases/tag/5.21.0.575-semiclip-fix) ... (updated one)!

**Pull request closed without merging**
