### PR TITLE
Add CVar: mp_afk_bomb_drop_time.

### PR DESCRIPTION
**Pull request by wopox1337**
Player that have never moved sience they last move will drop the bomb after this amount of time. (in seconds).

### CODE REVIEW

**Comment by Karaulov** [comment]
Player drop c4 even if not afk. (Just stay on place and aiming)

**Comment by wopox1337** [comment]
@Karaulov when player Aiming:
```
(m_pPlayer->pev->button & IN_ATTACK2))
{
	SecondaryAttack();
}
```

**Comment by Karaulov** [comment]
Every 5 second? 

And if player moving with SHIFT/CTRL, c4 dropped.

**Comment by Karaulov** [comment]
On next round, player drop bomb))))) at round start)))

**Comment by Karaulov** [comment]
@wopox1337 On next round, player drop bomb))))) at round start)))

**Pull request merged**
